name: CI

on:
  push:
    branches: ["main"]
    paths:
      - "application/**"
  pull_request:
    paths:
      - "application/**"
  workflow_dispatch:
  workflow_call:

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: application

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: application/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run Unit Tests (Client-side)
        run: npm run test

      - name: Run Server-side Tests
        run: npm run test:server

      - name: Build Application
        run: npm run build
