name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  deploy:
    needs: ci
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Export environment secrets and variables
        env:
          SECRETS_JSON: ${{ toJson(secrets) }}
          VARS_JSON: ${{ toJson(vars) }}
        run: |
          # Convert JSON to "KEY=VALUE" lines and append to GITHUB_ENV
          echo "$VARS_JSON" | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' >> $GITHUB_ENV
          echo "$SECRETS_JSON" | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' >> $GITHUB_ENV

      - name: Add computed app metadata vars
        run: |
          echo "APP_NAME=do-starter-kit-${{ inputs.environment }}" >> $GITHUB_ENV
          echo "DB_NAME=do-starter-kit-db-${{ inputs.environment }}" >> $GITHUB_ENV
          echo "CLUSTER_NAME=do-starter-kit-cluster-${{ inputs.environment }}" >> $GITHUB_ENV
          echo "GITHUB_BRANCH=${{ github.ref_name || 'main' }}" >> $GITHUB_ENV

      - name: Generate app.yaml from template
        run: envsubst < .do/app.template.yaml > .do/app.yaml

      - name: Restore DO bindable refs (APP_URL)
        run: sed -i 's|__APP_URL_BIND__|${APP_URL}|g' .do/app.yaml

      - name: Deploy to DigitalOcean App Platform
        uses: digitalocean/app_action/deploy@v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}
          app_spec_location: .do/app.yaml
          print_build_logs: true
